### ISSUE TITLE
AutoVacuum interval

### ISSUE THREAD

**Issue by tracker1** [DominicTobias/keshi#2]
Would be nice to be able to set an interval to auto-vacuum the cache, calling all isStale methods as available and removing all stale items from memory, in the case of node, if GC is available even forcing GC.

**Comment by DominicTobias** [comment]
Actually it is already doing this, I didn't document it but you can either turn it off or control how often it does it (default is 5mins):

```js
const cache = createCache('1 hour');
const cache = createCache(false); // off
```
